services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sp_sql_server_container
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SeriesPage123  
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  
    volumes:
      - sp_sql_data:/var/opt/mssql  

  redis:
    image: redis:latest
    container_name: sp_redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - sp_redis_data:/data

volumes:
  sp_sql_data:
    driver: local
    
  sp_redis_data:
    driver: local